# Shape
size: 64
input_length: 10
target_length: 10
spatial_depth: 0

# Model
dim_dynamic: 128
dim_appearance: 128
layers_encoder: [3, 5, 3]
ode_out_dim: 128
ode_hidden_dim: 256
augment_dim: 0
out_channels: 1

# Training parameters
batch_size: 32
epochs: 2000
lr_ae: 0.000001
lr_ode: 0.00001
decay_rate: 0.9
step_decay: 300
reg_lambda: 0.00001

# Save parameters
root_model: "run/Diff_opt_10_10__image_focus_slow/models/"
root_images: "run/Diff_opt_10_10__image_focus_slow/images/"
checkpoint_image_interval: 50
checkpoint_name: "convnode_appearance64_"
checkpoint_model_interval: 100

