# Shape
size: 64
input_length: 10
target_length: 10
spatial_depth: 2

# Model
dim_dynamic: 128
dim_appearance: 128
layers_encoder: [3, 5, 3]
ode_out_dim: 128
ode_hidden_dim: 256
augment_dim: 0
out_channels: 3

# Training parameters
batch_size: 64
epochs: 2000
lr: 0.00005
decay_rate: 0.75
step_decay: 300
reg_lambda: 0.00001

# Save parameters
root_model: "run/Classic_10_10_2_bis/models/"
root_images: "run/Classic_10_10_2_bis/images/"
checkpoint_image_interval: 50
checkpoint_name: "convnode_appearance64_"
checkpoint_model_interval: 100

