# Shape
size: 64
input_length: 10
target_length: 10
spatial_depth: 0

# Model
dim_dynamic: 64
dim_appearance: 64
layers_encoder: [3, 5, 3]
ode_out_dim: 64
ode_hidden_dim: 128
augment_dim: 0
out_channels: 1

# Training parameters
batch_size: 32
epochs: 2000
lr: 0.00001
decay_rate: 0.95
step_decay: 300
reg_lambda: 0.00001

# Save parameters
root_model: "run/Classic_10_10_0_image_focus_slow_v2/models/"
root_images: "run/Classic_10_10_0_image_focus_slow_v2/images/"
checkpoint_image_interval: 50
checkpoint_name: "convnode_appearance64_"
checkpoint_model_interval: 100

