# Shape
size: 64
input_length: 10
target_length: 10

# Model
dim_dynamic: 128
dim_appearance: 128
layers_encoder: [3, 5, 3]
ode_out_dim: 128
ode_hidden_dim: 256
augment_dim: 0
out_channels: 3

# Training parameters
batch_size: 64
epochs: 2000
lr: 0.0001
lr_discriminators: 0.0005
decay_rate: 0.8
step_decay: 250
reg_lambda: 0.00001

# Save parameters
root_model: "run/ADV_2_18/models/"
root_images: "run/ADV_2_18/images/"
checkpoint_image_interval: 20
checkpoint_name: "convnode_appearance64"
checkpoint_model_interval: 100

